title: Decatur Supper Club
description: The Decatur Supper Club is a potluck-style gathering of friends, new and old, sharing meals and building community in and around Decatur, GA.
baseurl: ""
url: "https://decatursupperclub.github.io"
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  dinner_parties:
    output: true
    permalink: /dinner-parties/:name/

defaults:
  - scope:
      path: ""
      type: "dinner_parties"
    values:
      layout: "default"